apiVersion: v1
kind: Pod
metadata:
  name: next-pod
spec:
  containers:
  - name: next-app
    image: ved104/next-argo:2755b229f172c83c27277f42412823f6e75594ca
    ports:
    - containerPort: 3000
    
